name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_preview:
    env:
      ACTIONS_INSTALL_COMMAND: npm install
      ACTIONS_BUILD_COMMAND: npm run build
      ACTIONS_LOCK_FILE: package-lock.json
      ACTIONS_NODE_VERSION: 12.x
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.ACTIONS_NODE_VERSION }}
      - name: install dependencies
        run: ${{ env.ACTIONS_INSTALL_COMMAND }}
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles(format('**/{0}',env.ACTIONS_LOCK_FILE)) }}
          restore-keys: ${{ runner.os }}-node-
      - name: build
        run: ${{ env.ACTIONS_BUILD_COMMAND }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FOLLOWER_GRAPH }}'
          projectId: follower-graph
